"""Per-source Postgres schemas for partner-harvested data.

Each partner source (mipibu, povos-indigenas-rn, …) gets its own Postgres
schema ``src_<slug>`` holding an identical 4-table template
(``aggregated_records``, ``harvest_runs``, ``harvest_errors``,
``federation_cache``). The models declare a symbolic schema ``"source"``
(see ``app/models/aggregated_record.py``); this module rewrites it:

* **Postgres, one source at a time** — :func:`bind_source` points the
  current session's connection at ``src_<slug>`` for the duration of a
  write operation (harvest, reextract, federation cache).
* **SQLite (dev + tests)** — the engine carries a global
  ``schema_translate_map`` (set in :mod:`app.config`) that collapses
  ``"source"`` to the single namespace; :func:`bind_source` is a no-op.

Cross-source reads go through the ``*_all`` UNION views in ``public``
(:mod:`app.models._views`), regenerated by :func:`rebuild_source_views`.

Full design: ``docs/partner-schema-design.md``.
"""
from __future__ import annotations

import contextvars
import re

from contextlib import nullcontext

from sqlalchemy import event, text
from sqlalchemy.engine import Connection, Engine

from ..extensions import db
from ..models import AggregatedRecord, FederationCache, HarvestError, HarvestRun

# The schema the symbolic ``"source"`` resolves to for the current
# context (thread / async task / greenlet). Set by :func:`bind_source`,
# read by the ``engine_connect`` listener below so it survives across the
# commits a harvest / federation-fetch does mid-operation.
_current_source_schema: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "brasil_current_source_schema", default=None
)


@event.listens_for(Engine, "engine_connect")
def _apply_source_translate(connection) -> None:  # pragma: no cover - exercised via routes
    if connection.dialect.name != "postgresql":
        return
    existing = connection.get_execution_options().get("schema_translate_map") or {}
    if "source" in existing:  # engine already pins it (the test suite) — leave it
        return
    schema = _current_source_schema.get()
    if schema:
        connection.execution_options(
            schema_translate_map={"source": schema}
        )

# Order matters for CREATE (parents first) — harvest_runs before its children.
_PER_SOURCE = (HarvestRun, AggregatedRecord, HarvestError, FederationCache)

_VIEWS = ("aggregated_records", "harvest_runs", "harvest_errors")

_SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


def source_schema(slug: str) -> str:
    """``mipibu`` -> ``src_mipibu``; ``povos-indigenas-rn`` -> ``src_povos_indigenas_rn``."""
    if not _SLUG_RE.match(slug or ""):
        raise ValueError(f"unsafe source slug: {slug!r}")
    return "src_" + slug.replace("-", "_")


def _is_pg(engine_or_conn) -> bool:
    return engine_or_conn.dialect.name == "postgresql"


def reset_source() -> None:
    """Forget the current source binding. Wired to Flask's app-context
    teardown so a stale binding can't leak from one request to the next."""
    _current_source_schema.set(None)


# --------------------------------------------------------------------------- #
# runtime: point the session at one source
# --------------------------------------------------------------------------- #

def bind_source(slug: str) -> None:
    """Route ``source.*`` reads/writes on the current session to one source.

    Postgres only — sets a connection-wide ``schema_translate_map``. On
    SQLite the engine's global map already collapses ``"source"``, so this
    is a no-op. The map is connection-wide, so **do not mix two sources'
    writes in one transaction** (nothing in the codebase does).
    """
    if not _is_pg(db.engine):
        return
    # If the engine already pins "source" to a fixed schema (the test
    # suite uses one shared src_test), leave it — there's nothing to route.
    fixed = db.engine.get_execution_options().get("schema_translate_map") or {}
    if "source" in fixed:
        return
    schema = source_schema(slug)
    _current_source_schema.set(schema)
    # Apply to the connection already checked out this request/txn, if any —
    # future checkouts pick it up via the engine_connect listener.
    conn = db.session.connection()
    if (conn.get_execution_options().get("schema_translate_map") or {}).get(
        "source"
    ) != schema:
        conn.execution_options(schema_translate_map={"source": schema})


# --------------------------------------------------------------------------- #
# stamping / dropping a source schema (Postgres only)
# --------------------------------------------------------------------------- #

def ensure_source_schema(engine: Engine, slug: str) -> None:
    """Create ``src_<slug>`` and its 4 tables from the current model metadata.

    Idempotent. No-op on SQLite, and no-op when the engine pins ``"source"``
    to a fixed schema (the test suite's single ``src_test``).
    """
    if not _is_pg(engine) or _fixed_source_schema(engine) is not False:
        return
    schema = source_schema(slug)
    tables = [m.__table__ for m in _PER_SOURCE]
    with engine.begin() as conn:
        conn.execute(text(f'CREATE SCHEMA IF NOT EXISTS "{schema}"'))
        conn = conn.execution_options(schema_translate_map={"source": schema})
        db.metadata.create_all(conn, tables=tables, checkfirst=True)


def drop_source_schema(engine: Engine, slug: str) -> None:
    """``DROP SCHEMA src_<slug> CASCADE`` — de-register a source. Operator action."""
    if not _is_pg(engine):
        return
    schema = source_schema(slug)
    with engine.begin() as conn:
        conn.execute(text(f'DROP SCHEMA IF EXISTS "{schema}" CASCADE'))


# --------------------------------------------------------------------------- #
# cross-source read layer: public.<name>_all views
# --------------------------------------------------------------------------- #

def _registered_slugs() -> list[str]:
    from ..models import UpgradeProject

    return sorted(
        db.session.scalars(db.select(UpgradeProject.slug)).all()
    )


def _fixed_source_schema(engine: Engine):
    """The engine's pinned ``"source"`` schema, or ``False`` if unpinned.

    ``None``       — SQLite: the four models share the one namespace.
    ``"src_test"`` — the Postgres test suite: one shared source schema.
    ``False``      — Postgres runtime: real per-source ``src_<slug>`` schemas,
                     so the views UNION over the registered slugs.
    """
    m = engine.get_execution_options().get("schema_translate_map") or {}
    return m["source"] if "source" in m else False


def _join_body(view: str, tbl_prefix: str) -> str:
    """JOIN form — one shared table, attributed via ``upgrade_projects``.
    ``tbl_prefix`` is ``''`` (SQLite) or ``'"src_test".'`` (PG test).
    ``source_slug`` is cast so every view form agrees on its type."""
    slug = "CAST(up.slug AS TEXT) AS source_slug"
    if view == "harvest_errors":  # no upgrade_project_id — hop through the run
        return (
            f'SELECT t.*, {slug} '
            f'FROM {tbl_prefix}"harvest_errors" t '
            f'JOIN {tbl_prefix}"harvest_runs" hr ON hr.id = t.harvest_run_id '
            f'JOIN "upgrade_projects" up ON up.id = hr.upgrade_project_id'
        )
    return (
        f'SELECT t.*, {slug} '
        f'FROM {tbl_prefix}"{view}" t '
        f'JOIN "upgrade_projects" up ON up.id = t.upgrade_project_id'
    )


def _union_body(view: str, slugs: list[str]) -> str:
    """UNION form — one branch per registered source's ``src_<slug>`` schema."""
    if not slugs:  # typed empty stub so a fresh DB never breaks dependent queries
        model = {m.__tablename__: m for m in _PER_SOURCE}[view]
        cols = ", ".join(
            f'CAST(NULL AS {c.type.compile(dialect=db.engine.dialect)}) AS "{c.name}"'
            for c in model.__table__.columns
        )
        return f"SELECT {cols}, CAST(NULL AS TEXT) AS source_slug WHERE false"
    return " UNION ALL ".join(
        f"SELECT t.*, CAST('{s}' AS TEXT) AS source_slug "
        f'FROM "{source_schema(s)}"."{view}" t'
        for s in slugs
    )


def rebuild_source_views(
    bind: Engine | Connection, slugs: list[str] | None = None
) -> None:
    """(Re)create the three ``public.*_all`` views. Idempotent. Call after any
    change to the registered source list (folded into
    ``scripts/load_upgrade_projects``), from the initial migration, and in
    the test fixture.

    ``bind`` may be an Engine or an already-open Connection (migrations pass
    ``op.get_bind()``). ``slugs`` — the registered source slugs for the
    Postgres-runtime UNION; defaults to reading them from
    ``public.upgrade_projects`` (needs an app context). Ignored on SQLite /
    the fixed-schema test mode.
    """
    fixed = _fixed_source_schema(bind)
    is_pg = _is_pg(bind)

    def _body(view: str) -> str:
        if fixed is False:  # Postgres runtime — per-source UNION
            resolved = slugs if slugs is not None else _registered_slugs()
            return _union_body(view, resolved)
        prefix = f'"{fixed}".' if fixed else ""  # 'src_test' or SQLite bare
        return _join_body(view, prefix)

    ctx = bind.begin() if isinstance(bind, Engine) else nullcontext(bind)
    with ctx as conn:
        for view in _VIEWS:
            name = f'public."{view}_all"' if is_pg else f'"{view}_all"'
            # DROP + CREATE (not CREATE OR REPLACE) so a column-type change
            # between rebuilds — e.g. the empty stub vs a populated UNION —
            # is not rejected.
            conn.execute(
                text(f"DROP VIEW IF EXISTS {name}" + (" CASCADE" if is_pg else ""))
            )
            conn.execute(text(f"CREATE VIEW {name} AS {_body(view)}"))


def drop_source_views(engine: Engine) -> None:
    """Drop the three ``*_all`` views. Call before ``db.drop_all()`` in
    tests — on Postgres the views depend on the ``src_test.*`` tables, so
    ``DROP TABLE`` fails while a view still references them."""
    if _is_pg(engine):
        stmts = [f'DROP VIEW IF EXISTS public."{v}_all" CASCADE' for v in _VIEWS]
    else:
        stmts = [f'DROP VIEW IF EXISTS "{v}_all"' for v in _VIEWS]  # SQLite: no CASCADE
    with engine.begin() as conn:
        for stmt in stmts:
            conn.execute(text(stmt))
