"""Initial schema per docs/schema-v1.md

Revision ID: 68facc4f886d
Revises: 
Create Date: 2026-08-24 22:28:29.320136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68facc4f886d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label_en', sa.String(), nullable=False),
    sa.Column('label_pt', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label_en', sa.String(), nullable=False),
    sa.Column('label_pt', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('record_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label_en', sa.String(), nullable=False),
    sa.Column('label_pt', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('label_en', sa.String(), nullable=False),
    sa.Column('label_pt', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('provisional', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_pt', sa.String(), nullable=True),
    sa.Column('handle_prefix', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('ark_identifier', sa.String(), nullable=True),
    sa.Column('viaf_id', sa.String(), nullable=True),
    sa.Column('isni_id', sa.String(), nullable=True),
    sa.Column('wikidata_qid', sa.String(), nullable=True),
    sa.Column('geonames_primary_id', sa.Integer(), nullable=True),
    sa.Column('institutional_type_id', sa.Integer(), nullable=False),
    sa.Column('home_country_code', sa.String(), nullable=False),
    sa.Column('home_state_code', sa.String(), nullable=True),
    sa.Column('home_city', sa.String(), nullable=True),
    sa.Column('canonical_url', sa.String(), nullable=False),
    sa.Column('catalog_url', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('oai_pmh_base_url', sa.String(), nullable=True),
    sa.Column('ead_finding_aid_url', sa.String(), nullable=True),
    sa.Column('iiif_manifest_root', sa.String(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_pt', sa.Text(), nullable=True),
    sa.Column('curatorial_rarity_notes', sa.Text(), nullable=True),
    sa.Column('prior_use_note', sa.Text(), nullable=True),
    sa.Column('stated_scope', sa.Text(), nullable=True),
    sa.Column('no_digital_content', sa.Boolean(), nullable=False),
    sa.Column('fair_use_eligible', sa.Boolean(), nullable=True),
    sa.Column('caveat_emptor', sa.Boolean(), nullable=False),
    sa.Column('survey_source', sa.String(), nullable=True),
    sa.Column('survey_row', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institutional_type_id'], ['institutional_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('archive_periods',
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.PrimaryKeyConstraint('archive_id', 'period_id')
    )
    op.create_table('archive_record_types',
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('record_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.ForeignKeyConstraint(['record_type_id'], ['record_types.id'], ),
    sa.PrimaryKeyConstraint('archive_id', 'record_type_id')
    )
    op.create_table('archive_themes',
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ),
    sa.PrimaryKeyConstraint('archive_id', 'theme_id')
    )
    op.create_table('dimension_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('justification_en', sa.Text(), nullable=False),
    sa.Column('justification_pt', sa.Text(), nullable=True),
    sa.Column('scored_by', sa.String(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("dimension IN ('accessibility','provenance_curatorial','corpus_completeness','finding_aids','pipeline_ingestion_readiness','uniqueness_non_duplication','scale','linkage_potential')", name='ck_dimension_scores_dimension'),
    sa.CheckConstraint('score >= 0 AND score <= 10', name='ck_dimension_scores_range'),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['dimension_scores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dimension_scores', schema=None) as batch_op:
        batch_op.create_index('idx_dimension_scores_active', ['archive_id', 'dimension'], unique=False, sqlite_where=sa.text('superseded_at IS NULL'), postgresql_where=sa.text('superseded_at IS NULL'))

    op.create_table('facet_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=False),
    sa.Column('facet', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('set_by', sa.String(), nullable=True),
    sa.Column('set_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['facet_values.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facet_values', schema=None) as batch_op:
        batch_op.create_index('idx_facet_values_active', ['archive_id', 'facet'], unique=False, sqlite_where=sa.text('superseded_at IS NULL'), postgresql_where=sa.text('superseded_at IS NULL'))

    op.create_table('upgrade_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_pt', sa.String(), nullable=True),
    sa.Column('source_archive_id', sa.Integer(), nullable=False),
    sa.Column('scope_description_en', sa.Text(), nullable=False),
    sa.Column('scope_description_pt', sa.Text(), nullable=True),
    sa.Column('approximate_document_count', sa.Integer(), nullable=True),
    sa.Column('approximate_page_equivalents', sa.Integer(), nullable=True),
    sa.Column('primary_url', sa.String(), nullable=False),
    sa.Column('source_repo', sa.String(), nullable=True),
    sa.Column('delivery_status', sa.String(), nullable=False),
    sa.Column('federation_contract_version', sa.String(), nullable=False),
    sa.Column('oai_pmh_base_url', sa.String(), nullable=True),
    sa.Column('iiif_search_endpoint', sa.String(), nullable=True),
    sa.Column('ead_export_url', sa.String(), nullable=True),
    sa.Column('eac_cpf_export_url', sa.String(), nullable=True),
    sa.Column('supported_metadata_formats', sa.String(), nullable=True),
    sa.Column('supported_authorities', sa.String(), nullable=True),
    sa.Column('code_license', sa.String(), nullable=True),
    sa.Column('data_license', sa.String(), nullable=True),
    sa.Column('attribution_required', sa.Boolean(), nullable=False),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('maintainer', sa.String(), nullable=True),
    sa.Column('yaml_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_archive_id'], ['archives.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('dimension_lifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upgrade_project_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=False),
    sa.Column('source_archive_score', sa.Integer(), nullable=False),
    sa.Column('upgrade_score', sa.Integer(), nullable=False),
    sa.Column('justification_en', sa.Text(), nullable=False),
    sa.Column('justification_pt', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('source_archive_score >= 0 AND source_archive_score <= 10', name='ck_dimension_lifts_source_range'),
    sa.CheckConstraint('upgrade_score >= 0 AND upgrade_score <= 10', name='ck_dimension_lifts_upgrade_range'),
    sa.ForeignKeyConstraint(['upgrade_project_id'], ['upgrade_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('probe_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archive_id', sa.Integer(), nullable=True),
    sa.Column('upgrade_project_id', sa.Integer(), nullable=True),
    sa.Column('probed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('canonical_url', sa.String(), nullable=False),
    sa.Column('https_valid', sa.Boolean(), nullable=True),
    sa.Column('cert_expires_at', sa.Date(), nullable=True),
    sa.Column('canonical_http_status', sa.Integer(), nullable=True),
    sa.Column('interior_url_sample', sa.Text(), nullable=True),
    sa.Column('interior_http_statuses', sa.Text(), nullable=True),
    sa.Column('oai_pmh_identify_ok', sa.Boolean(), nullable=True),
    sa.Column('oai_pmh_earliest_datestamp', sa.Date(), nullable=True),
    sa.Column('oai_pmh_record_count', sa.Integer(), nullable=True),
    sa.Column('iiif_search_endpoint_ok', sa.Boolean(), nullable=True),
    sa.Column('wayback_home_count', sa.Integer(), nullable=True),
    sa.Column('wayback_interior_hit_ratio', sa.Float(), nullable=True),
    sa.Column('directory_url_count_now', sa.Integer(), nullable=True),
    sa.Column('directory_url_count_12m_ago', sa.Integer(), nullable=True),
    sa.Column('directory_url_count_24m_ago', sa.Integer(), nullable=True),
    sa.Column('citation_count_crossref', sa.Integer(), nullable=True),
    sa.Column('citation_count_semantic_scholar', sa.Integer(), nullable=True),
    sa.Column('web_ops_health', sa.String(), nullable=True),
    sa.Column('external_preservation', sa.String(), nullable=True),
    sa.Column('growth_signal', sa.String(), nullable=True),
    sa.Column('prior_use_signal', sa.String(), nullable=True),
    sa.Column('probe_version', sa.String(), nullable=False),
    sa.Column('probe_notes', sa.Text(), nullable=True),
    sa.CheckConstraint('(archive_id IS NOT NULL) OR (upgrade_project_id IS NOT NULL)', name='ck_probe_results_target'),
    sa.ForeignKeyConstraint(['archive_id'], ['archives.id'], ),
    sa.ForeignKeyConstraint(['upgrade_project_id'], ['upgrade_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('probe_results', schema=None) as batch_op:
        batch_op.create_index('idx_probe_results_archive_time', ['archive_id', 'probed_at'], unique=False)
        batch_op.create_index('idx_probe_results_upgrade_time', ['upgrade_project_id', 'probed_at'], unique=False)

    op.create_table('upgrade_project_periods',
    sa.Column('upgrade_project_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['upgrade_project_id'], ['upgrade_projects.id'], ),
    sa.PrimaryKeyConstraint('upgrade_project_id', 'period_id')
    )
    op.create_table('upgrade_project_record_types',
    sa.Column('upgrade_project_id', sa.Integer(), nullable=False),
    sa.Column('record_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['record_type_id'], ['record_types.id'], ),
    sa.ForeignKeyConstraint(['upgrade_project_id'], ['upgrade_projects.id'], ),
    sa.PrimaryKeyConstraint('upgrade_project_id', 'record_type_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upgrade_project_record_types')
    op.drop_table('upgrade_project_periods')
    with op.batch_alter_table('probe_results', schema=None) as batch_op:
        batch_op.drop_index('idx_probe_results_upgrade_time')
        batch_op.drop_index('idx_probe_results_archive_time')

    op.drop_table('probe_results')
    op.drop_table('dimension_lifts')
    op.drop_table('upgrade_projects')
    with op.batch_alter_table('facet_values', schema=None) as batch_op:
        batch_op.drop_index('idx_facet_values_active', sqlite_where=sa.text('superseded_at IS NULL'), postgresql_where=sa.text('superseded_at IS NULL'))

    op.drop_table('facet_values')
    with op.batch_alter_table('dimension_scores', schema=None) as batch_op:
        batch_op.drop_index('idx_dimension_scores_active', sqlite_where=sa.text('superseded_at IS NULL'), postgresql_where=sa.text('superseded_at IS NULL'))

    op.drop_table('dimension_scores')
    op.drop_table('archive_themes')
    op.drop_table('archive_record_types')
    op.drop_table('archive_periods')
    op.drop_table('archives')
    op.drop_table('themes')
    op.drop_table('record_types')
    op.drop_table('periods')
    op.drop_table('institutional_types')
    # ### end Alembic commands ###
