"""add federation_cache table and json_api_base_url column

Revision ID: b0fd625449a7
Revises: 68facc4f886d
Create Date: 2026-08-26 00:46:14.654326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fd625449a7'
down_revision = '68facc4f886d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upgrade_project_id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('request_url', sa.String(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('contract_version', sa.String(), nullable=True),
    sa.Column('corpus_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_project_id'], ['upgrade_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upgrade_project_id', 'cache_key', name='uq_federation_cache_project_key')
    )
    with op.batch_alter_table('upgrade_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_api_base_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upgrade_projects', schema=None) as batch_op:
        batch_op.drop_column('json_api_base_url')

    op.drop_table('federation_cache')
    # ### end Alembic commands ###
