"""add aggregated_records + harvest_runs + harvest_errors tables

Revision ID: ca94209a1f1b
Revises: b0fd625449a7
Create Date: 2026-08-26 21:13:36.340922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca94209a1f1b'
down_revision = 'b0fd625449a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upgrade_project_id', sa.Integer(), nullable=False),
    sa.Column('metadata_prefix', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_upserted', sa.Integer(), nullable=False),
    sa.Column('records_unchanged', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('from_ts', sa.String(), nullable=True),
    sa.Column('until_ts', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['upgrade_project_id'], ['upgrade_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('harvest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harvest_runs_upgrade_project_id'), ['upgrade_project_id'], unique=False)

    op.create_table('aggregated_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upgrade_project_id', sa.Integer(), nullable=False),
    sa.Column('oai_identifier', sa.String(), nullable=False),
    sa.Column('metadata_prefix', sa.String(), nullable=False),
    sa.Column('datestamp', sa.String(), nullable=False),
    sa.Column('set_specs_json', sa.Text(), nullable=False),
    sa.Column('raw_xml', sa.Text(), nullable=False),
    sa.Column('raw_xml_sha256', sa.String(), nullable=False),
    sa.Column('extracted_json', sa.Text(), nullable=False),
    sa.Column('harvest_run_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['harvest_run_id'], ['harvest_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upgrade_project_id'], ['upgrade_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upgrade_project_id', 'oai_identifier', 'metadata_prefix', name='uq_aggregated_records_identity')
    )
    with op.batch_alter_table('aggregated_records', schema=None) as batch_op:
        batch_op.create_index('ix_aggregated_records_project_datestamp', ['upgrade_project_id', 'datestamp'], unique=False)
        batch_op.create_index('ix_aggregated_records_sha', ['raw_xml_sha256'], unique=False)

    op.create_table('harvest_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('harvest_run_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('oai_identifier', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('xml_excerpt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['harvest_run_id'], ['harvest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('harvest_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harvest_errors_harvest_run_id'), ['harvest_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harvest_errors_harvest_run_id'))

    op.drop_table('harvest_errors')
    with op.batch_alter_table('aggregated_records', schema=None) as batch_op:
        batch_op.drop_index('ix_aggregated_records_sha')
        batch_op.drop_index('ix_aggregated_records_project_datestamp')

    op.drop_table('aggregated_records')
    with op.batch_alter_table('harvest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harvest_runs_upgrade_project_id'))

    op.drop_table('harvest_runs')
    # ### end Alembic commands ###
